# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90ba0645e687ce5758baf89039586ff46b991161cdbab14ec1108f4769a6c80e85c77f2fc755cdd5191fd1b749743b2a147b8299fb53ace9262d8615e1ba671d

test:
  secret_key_base: f10c217916a7ee7b99e4b4c66afc38a4a2d6799d2e3ba8400c91396033c203184239448a3c53a0dc0cb2a34ba51a33df4c29f7b8e68361dc0e0664aa9835b6ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
